<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>37cd2a8f-ff87-4ae1-8a0d-1b43c427577e</groupId>
		<artifactId>bg-parent-pom</artifactId>
		<version>2.2.0</version>
	</parent>
	<groupId>com.centrica</groupId>
	<artifactId>bg-premise-ensek-sys-api</artifactId>
	<version>1.5.1-SNAPSHOT</version>
	<packaging>mule-application</packaging>

	<name>${project.artifactId}-${app.version}</name>

	<properties>
		<app.version>v1</app.version>
		<app.runtime>4.6-java8</app.runtime>
		<app.releaseChannel>LTS</app.releaseChannel>
		<asset.version>1.0.5</asset.version>
	</properties>

	<build>
		<finalName>${project.artifactId}-${app.version}</finalName>
		<plugins>
			<plugin>
				<groupId>com.mulesoft.munit.tools</groupId>
				<artifactId>munit-maven-plugin</artifactId>
				<configuration>
					<coverage>
						<ignoreFlows>
							<ignoreFlow>global-error-handler</ignoreFlow>
						</ignoreFlows>
					</coverage>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<cloudHubDeployment>
						<uri>https://anypoint.mulesoft.com</uri>
						<muleVersion>${app.runtime}</muleVersion>
						<connectedAppClientId>${anypoint.username}</connectedAppClientId>
						<connectedAppClientSecret>${anypoint.password}</connectedAppClientSecret>
						<connectedAppGrantType>client_credentials</connectedAppGrantType>
						<applicationName>${app_name}</applicationName>
						<environment>${env_platform}</environment>
						<businessGroupId>${b2c.groupId}</businessGroupId>
						<workerType>${worker_type}</workerType>
						<region>eu-west-2</region>
						<workers>${workers}</workers>
						<objectStoreV2>true</objectStoreV2>
						<disableCloudHubLogs>true</disableCloudHubLogs>
						<!--Setting skipDeploymentVerification as true to not waste pipeline resources. Developer/whoever does release to production needs to ensure the app is up by checking status either by calling platform apis/runtime manager -->
						<skipDeploymentVerification>true</skipDeploymentVerification>
						<!-- Start: Non-Encrypted properties -->
						<properties>
							<encryptionKey>${encryption_key}</encryptionKey>
							<env>${env_property_file}</env>
							<anypoint.platform.config.analytics.agent.enabled>true</anypoint.platform.config.analytics.agent.enabled>
							<anypoint.platform.client_id>${platform_clientid}</anypoint.platform.client_id>
							<anypoint.platform.client_secret>${platform_clientsecret}</anypoint.platform.client_secret>
							<ensek.aws.accesskey>${ensek_accesskey}</ensek.aws.accesskey>
							<ensek.aws.secretkey>${ensek_secretkey}</ensek.aws.secretkey>
							<!-- OTEL configs -->
							<opentelemetry.endpointToken>${opentelemetry_endpointToken}</opentelemetry.endpointToken>
							<opentelemetry.metrics.anypoint.clientId>${opentelemetry_metrics_anypoint_clientId}</opentelemetry.metrics.anypoint.clientId>
							<opentelemetry.metrics.anypoint.clientSecret>${opentelemetry_metrics_anypoint_clientSecret}</opentelemetry.metrics.anypoint.clientSecret>
						</properties>
						<!-- End: Non-Encrypted properties -->
					</cloudHubDeployment>
					<classifier>mule-application</classifier>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-validation-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>${b2c.groupId}</groupId>
			<artifactId>awsv4auth-extension-v1</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>${b2c.groupId}</groupId>
			<artifactId>${project.artifactId}</artifactId>
			<version>${asset.version}</version>
			<classifier>raml</classifier>
			<type>zip</type>
		</dependency>
		<!-- MUNIT TESTS -->
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>${b2c.groupId}</groupId>
			<artifactId>bg-common-library</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.britishgasenergy</groupId>
			<artifactId>bg-otel-library</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange V3</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
	</repositories>
</project>
